parameters:
  hateoas.resource_cache.class: GoIntegro\Bundle\HateoasBundle\JsonApi\ArrayResourceCache
  hateoas.metadata_cache.class: GoIntegro\Bundle\HateoasBundle\Metadata\Entity\ArrayMetadataCache

services:
  hateoas.request_parser:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\Parser
    scope: request
    arguments:
      - @request
      - @hateoas.request_parser.filter
      - @hateoas.request_parser.pagination
      - @hateoas.request_parser.body
      - @hateoas.request_parser.action
      - @hateoas.request_parser.entities
      - %api.url_path%
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.filter:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\FilterParser
    public: false
    arguments:
      - @hateoas.metadata_miner
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.pagination:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\PaginationParser
    public: false
    arguments:
      - @hateoas.metadata_miner
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.body:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\BodyParser
    public: false
    arguments:
      - @hateoas.json_coder
      - @hateoas.raml.finder
      - @doctrine.orm.entity_manager

  hateoas.request_parser.action:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\ActionParser
    public: false

  hateoas.request_parser.entities:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\ParamEntityFinder
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @security.context

  hateoas.metadata_miner:
    class: GoIntegro\Bundle\HateoasBundle\Metadata\Resource\MetadataMiner
    arguments: [@hateoas.miner_provider]

  hateoas.miner_provider:
    class: GoIntegro\Bundle\HateoasBundle\Metadata\Resource\MinerProvider
    arguments:
      - @hateoas.metadata_cache
      - %api.resource_class_path%

  hateoas.resource_manager:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\ResourceManager
    scope: request
    arguments:
      - @hateoas.resource_cache
      - @hateoas.metadata_miner
      - @hateoas.request_parser
      - @service_container
      - %api.url_path%

  hateoas.resource_cache:
    class: %hateoas.resource_cache.class%
    arguments:
      - @hateoas.metadata_cache
      - @hateoas.metadata_miner
      - @service_container
      - %api.resource_class_path%
      - %api.url_path%

  hateoas.metadata_cache:
    class: %hateoas.metadata_cache.class%
    arguments: [@doctrine.orm.entity_manager]

  hateoas.repo_helper:
    class: GoIntegro\Bundle\HateoasBundle\Util\RepositoryHelper
    arguments: [@doctrine.orm.entity_manager]

  hateoas.document_blender:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Merge\Blender
    arguments: [@hateoas.json_coder]

  hateoas.json_coder:
    class: GoIntegro\Bundle\HateoasBundle\Util\JsonCoder
    arguments: [@kernel]

  hateoas.entity.builder:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Builder
    scope: request

  hateoas.entity.default_builder:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultBuilder
    scope: request
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @validator
      - @security.context
      - @hateoas.request_parser
    tags:
      -  { name: hateoas.entity.builder, resource_type: default }

  hateoas.entity.mutator:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Mutator
    scope: request

  hateoas.entity.default_mutator:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultMutator
    scope: request
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @validator
      - @hateoas.request_parser
    tags:
      -  { name: hateoas.entity.mutator, resource_type: default }

  hateoas.entity.deleter:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Deleter
    scope: request

  hateoas.entity.default_deleter:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultDeleter
    scope: request
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @hateoas.request_parser
    tags:
      -  { name: hateoas.entity.deleter, resource_type: default }

  hateoas.raml.finder:
    class: GoIntegro\Bundle\HateoasBundle\Raml\DocFinder
    arguments:
      - @hateoas.raml.parser
      - @hateoas.json_coder
      - %go_integro_hateoas.json_api%

  hateoas.raml.parser:
    class: GoIntegro\Bundle\HateoasBundle\Raml\DocParser
    arguments:
      - @hateoas.json_coder
