parameters:
  hateoas.resource_cache.class: GoIntegro\Bundle\HateoasBundle\JsonApi\ArrayResourceCache
  hateoas.metadata_cache.class: GoIntegro\Bundle\HateoasBundle\Metadata\Entity\ArrayMetadataCache

services:
  hateoas.request_parser:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\Parser
    arguments:
      # @todo Could we not just pass the request as a parameter?
      - @hateoas.raml.finder
      - @hateoas.request_parser.filter
      - @hateoas.request_parser.pagination
      - @hateoas.request_parser.body
      - @hateoas.request_parser.action
      - @hateoas.request_parser.entities
      - @hateoas.request_parser.locale
      - @hateoas.metadata_miner
      - %api.url_path%
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.filter:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\FilterParser
    public: false
    arguments:
      - @hateoas.metadata_miner
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.pagination:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\PaginationParser
    public: false
    arguments:
      - @hateoas.metadata_miner
      - %go_integro_hateoas.json_api%

  hateoas.request_parser.body:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\BodyParser
    public: false
    arguments:
      - @hateoas.json_coder
      - @hateoas.raml.finder
      - @hateoas.request_parser.hydrant
      - @hateoas.request_parser.body.create
      - @hateoas.request_parser.body.update
      - @hateoas.request_parser.body.link
      - @hateoas.request_parser.body.unlink
      - @hateoas.request_parser.body.translations

  hateoas.request_parser.body.create:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\CreateBodyParser
    public: false

  hateoas.request_parser.body.update:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\UpdateBodyParser
    public: false

  hateoas.request_parser.body.link:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\LinkBodyParser
    public: false

  hateoas.request_parser.body.unlink:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\UnlinkBodyParser
    public: false

  hateoas.request_parser.body.translations:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\TranslationsParser
    public: false

  hateoas.request_parser.action:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\ActionParser
    public: false
    arguments:
      - @hateoas.json_coder
      - @hateoas.metadata_miner

  hateoas.request_parser.entities:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\ParamEntityFinder
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @security.context
      - @hateoas.json_coder

  hateoas.request_parser.locale:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\LocaleNegotiator
    public: false

  hateoas.request_parser.default_locale:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\DefaultLocaleNegotiator
    public: false
    tags:
      - { name: hateoas.request_parser.locale }

  hateoas.request_parser.hydrant:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\ResourceLinksHydrant
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @hateoas.metadata_miner

  hateoas.metadata_miner:
    class: GoIntegro\Bundle\HateoasBundle\Metadata\Resource\MetadataMiner
    arguments: [@hateoas.miner_provider]

  hateoas.miner_provider:
    class: GoIntegro\Bundle\HateoasBundle\Metadata\Resource\MinerProvider
    arguments:
      - @hateoas.metadata_cache
      - %api.resource_class_path%

  hateoas.resource_manager:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\ResourceManager
    arguments:
      - @hateoas.metadata_miner
      - @hateoas.resource_cache
      - @service_container
      - @security.context
      - %api.url_path%

  hateoas.resource_cache:
    class: %hateoas.resource_cache.class%
    arguments:
      - @hateoas.metadata_cache
      - @hateoas.metadata_miner
      - @service_container
      - %go_integro_hateoas.cache%

  hateoas.metadata_cache:
    class: %hateoas.metadata_cache.class%
    arguments: [@doctrine.orm.entity_manager]

  hateoas.repo_helper:
    class: GoIntegro\Bundle\HateoasBundle\Util\RepositoryHelper
    arguments: [@doctrine.orm.entity_manager]

  hateoas.repo_helper.default_filter:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Request\DefaultFilter
    public: false
    tags:
      - { name: hateoas.repo_helper.filter }

  hateoas.document_blender:
    class: GoIntegro\Bundle\HateoasBundle\JsonApi\Merge\Blender
    arguments: [@hateoas.json_coder]

  hateoas.json_coder:
    class: GoIntegro\Bundle\HateoasBundle\Util\JsonCoder
    arguments: [@kernel]

  hateoas.entity.builder:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Builder
    scope: request

  hateoas.entity.default_builder:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultBuilder
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @validator
      - @security.context
    tags:
      -  { name: hateoas.entity.builder, resource_type: default }

  hateoas.entity.mutator:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Mutator
    scope: request

  hateoas.entity.default_mutator:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultMutator
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @validator
    tags:
      -  { name: hateoas.entity.mutator, resource_type: default }

  hateoas.entity.deleter:
    class: GoIntegro\Bundle\HateoasBundle\Entity\Deleter

  hateoas.entity.default_deleter:
    class: GoIntegro\Bundle\HateoasBundle\Entity\DefaultDeleter
    public: false
    arguments:
      - @doctrine.orm.entity_manager
      - @hateoas.request_parser
    tags:
      -  { name: hateoas.entity.deleter, resource_type: default }

  hateoas.raml.finder:
    class: GoIntegro\Bundle\HateoasBundle\Raml\DocFinder
    arguments:
      - @hateoas.raml.parser
      - @hateoas.json_coder
      - %go_integro_hateoas.json_api%

  hateoas.raml.parser:
    class: GoIntegro\Bundle\HateoasBundle\Raml\DocParser
    arguments:
      - @hateoas.json_coder
